import { useEffect,useMemo,useState } from 'react';
import { X } from 'lucide-react';
import { useLocation,useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';

const visitorId=()=>{let id=localStorage.getItem('fw_promo_visitor');if(!id){id=(globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`);localStorage.setItem('fw_promo_visitor',id)}return id};
const device=()=>window.innerWidth<640?'mobile':window.innerWidth<1024?'tablet':'desktop';
const safePath=v=>typeof v==='string'&&v.startsWith('/')&&!v.startsWith('//')?v:null;
const excluded=path=>path==='/login'||path==='/forgot-password'||path==='/auth-callback'||path==='/my-account/promotions'||path.startsWith('/admin')||path.startsWith('/production')||path.startsWith('/legal/')||path==='/terms'||path==='/privacy'||path==='/website-terms'||path==='/mobile-terms';
const track=(name,path)=>{const u=new URL(window.location.href);return api.post('/promotion/event',{event:name,visitor_id:visitorId(),page:path||u.pathname,device:device(),source:u.searchParams.get('utm_source'),medium:u.searchParams.get('utm_medium'),campaign:u.searchParams.get('utm_campaign'),referrer:document.referrer||null}).catch(()=>{})};

export default function PromotionPopup(){const{user}=useAuth();const location=useLocation();const nav=useNavigate();const[cfg,setCfg]=useState(null);const[open,setOpen]=useState(false);const path=location.pathname;const seenKey=cfg?.promotion_id?`promo_seen_${cfg.promotion_id}`:null;const eligible=useMemo(()=>{if(!cfg?.is_live||excluded(path))return false;if(user)return path==='/world';return true},[cfg,user,path]);
 useEffect(()=>{api.get('/promotion/config').then(r=>setCfg(r.data)).catch(()=>{})},[]);
 useEffect(()=>{if(!cfg?.is_live||!eligible){setOpen(false);return}if(seenKey&&sessionStorage.getItem(seenKey)==='1'){setOpen(false);return}setOpen(true);track('impression',path)},[cfg?.promotion_id,cfg?.is_live,eligible,path,seenKey]);
 if(!cfg?.is_live||!eligible||!open)return null;
 const dismiss=()=>{track('close',path);if(seenKey)sessionStorage.setItem(seenKey,'1');setOpen(false)};
 const rememberIntent=(intent,next)=>{sessionStorage.setItem('fw_promo_intent',intent);sessionStorage.setItem('fw_promo_next',next);sessionStorage.setItem('fw_promo_origin',path);sessionStorage.setItem('fw_promo_signup_started','1');if(seenKey)sessionStorage.setItem(seenKey,'1')};
 const guest=(intent,next)=>{rememberIntent(intent,next);track('signup_start',path);nav(`/login?tab=signup&promo=${encodeURIComponent(intent)}&next=${encodeURIComponent(next)}`)};
 const join=()=>{track('join_click',path);if(seenKey)sessionStorage.setItem(seenKey,'1');setOpen(false);if(user){sessionStorage.removeItem('fw_promo_intent');sessionStorage.removeItem('fw_promo_next');nav('/my-account/promotions')}else guest('join','/my-account/promotions')};
 const refer=()=>{track('refer_click',path);if(seenKey)sessionStorage.setItem(seenKey,'1');setOpen(false);if(user){sessionStorage.removeItem('fw_promo_intent');sessionStorage.removeItem('fw_promo_next');nav('/refer')}else guest('refer','/refer')};
 const img=cfg.mobile_image_url||cfg.tablet_image_url||cfg.desktop_image_url;
 return <div className="fixed inset-0 z-[100] bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6 2xl:p-10" role="dialog" aria-modal="true" aria-label={cfg.name||'Promotion'}><div className="relative w-[92vw] sm:w-[85vw] lg:w-[80vw] 2xl:w-[76vw] max-w-5xl 2xl:max-w-[1800px] max-h-[90vh] overflow-hidden rounded-3xl 2xl:rounded-[2.5rem] bg-[#0B0D1F] shadow-2xl border border-white/10"><button onClick={dismiss} className="absolute right-3 top-3 2xl:right-5 2xl:top-5 z-10 rounded-full bg-black/65 hover:bg-black/80 p-2.5 2xl:p-4 text-white" aria-label="Close promotion"><X className="w-5 h-5 2xl:w-8 2xl:h-8"/></button><div className="h-[58vh] sm:h-[60vh] max-h-[60vh] bg-black/20">{img?<picture><source media="(min-width:1024px)" srcSet={cfg.desktop_image_url||img}/><source media="(min-width:640px)" srcSet={cfg.tablet_image_url||img}/><img src={img} alt={cfg.name||'Promotion'} className="w-full h-full object-cover"/></picture>:<div className="w-full h-full flex items-center justify-center text-white/40 text-center px-6 2xl:text-2xl">Promotion artwork will appear here</div>}</div><div className="min-h-[16vh] p-4 sm:p-6 2xl:p-9 grid grid-cols-1 sm:grid-cols-2 gap-3 2xl:gap-6 items-center bg-[#0B0D1F]"><button onClick={join} className="w-full py-4 2xl:py-6 rounded-xl 2xl:rounded-2xl bg-gradient-to-r from-[#FFD54A] to-[#FFB300] text-[#0B0D1F] font-black text-base sm:text-lg 2xl:text-2xl">JOIN CONTEST</button><button onClick={refer} className="w-full py-4 2xl:py-6 rounded-xl 2xl:rounded-2xl border-2 border-[#FFD54A] text-[#FFD54A] font-black text-base sm:text-lg 2xl:text-2xl">REFER A FRIEND</button></div></div></div>}
