import { useEffect,useRef,useState } from 'react';
import { api } from '../../lib/api';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const short=s=>s?`${s.slice(0,10)}…${s.slice(-8)}`:'—';

export default function PromotionDrawStudio(){
 const [status,setStatus]=useState(null),[phase,setPhase]=useState('ready'),[count,setCount]=useState(null),[ticker,setTicker]=useState('FW-XXXXXXXXXX'),[result,setResult]=useState(null),[revealed,setRevealed]=useState([]),[error,setError]=useState('');const timer=useRef(null);
 const load=async()=>{const d=(await api.get('/admin/promotion/draw')).data;setStatus(d);if(d.drawn){setResult(d.draw);setRevealed(d.draw.winners||[]);setPhase('complete')}};
 useEffect(()=>{load().catch(e=>setError(e?.response?.data?.detail||'Unable to load draw.'));return()=>clearInterval(timer.current)},[]);
 const fakeTicket=()=>`FW-${Array.from({length:10},()=>Math.floor(Math.random()*16).toString(16).toUpperCase()).join('')}`;
 const spin=()=>{clearInterval(timer.current);timer.current=setInterval(()=>setTicker(fakeTicket()),55)};const stopSpin=()=>clearInterval(timer.current);
 const start=async()=>{if(!status?.can_draw)return;setError('');setPhase('countdown');for(const n of [3,2,1]){setCount(n);await sleep(850)}setCount(null);setPhase('locking');await sleep(1200);setPhase('seeding');await sleep(1200);setPhase('rng');spin();let draw;try{draw=(await api.post('/admin/promotion/draw')).data;setResult(draw)}catch(e){stopSpin();setError(e?.response?.data?.detail||'Draw failed.');setPhase('ready');return}await sleep(2200);for(const w of draw.winners||[]){setPhase(`winner-${w.place}`);await sleep(1200);stopSpin();setTicker(w.ticket_number);setRevealed(x=>[...x,w]);await sleep(2600);if(w.place<(draw.winners||[]).length){setPhase('rng');spin();await sleep(1900)}}stopSpin();setPhase('complete')};
 if(!status)return <div className="fixed inset-0 bg-[#060711] text-white flex items-center justify-center">Loading Draw Studio…</div>;
 const prize=status.promotion?.prize_per_winner_gbp||500,total=(status.promotion?.winner_count||2)*prize;
 return <div className="fixed inset-0 z-[200] overflow-auto text-white bg-[#060711]" style={{backgroundImage:'radial-gradient(circle at 50% 10%,rgba(124,58,237,.28),transparent 38%),radial-gradient(circle at 15% 80%,rgba(234,179,8,.12),transparent 28%)'}}>
  <div className="min-h-screen flex flex-col p-6 md:p-10">
   <header className="flex items-center justify-between"><div><div className="text-yellow-400 font-black tracking-[.28em] text-xs md:text-sm">PRIZE LEAGUE • OFFICIAL DRAW</div><div className="text-white/40 text-xs mt-1">Cryptographically auditable RNG</div></div><button onClick={()=>window.location.href='/admin/promotion'} className="border border-white/15 bg-white/5 rounded-xl px-4 py-2 text-sm hover:bg-white/10">Exit Studio</button></header>
   <main className="flex-1 flex flex-col items-center justify-center text-center py-8">
    <div className="text-sm md:text-base uppercase tracking-[.35em] text-white/50">Free World Promotion</div><h1 className="mt-3 text-5xl md:text-8xl font-black tracking-tight">£{Number(total).toLocaleString()} <span className="text-yellow-400">DRAW</span></h1><p className="mt-3 text-white/50 text-lg">{status.promotion?.winner_count||2} winners • £{Number(prize).toLocaleString()} each</p>
    {phase==='countdown'&&<div className="my-10 text-[11rem] leading-none font-black text-yellow-400 animate-pulse">{count}</div>}
    {['locking','seeding','rng'].includes(phase)&&<div className="my-10 w-full max-w-4xl"><div className="text-violet-300 uppercase tracking-[.25em] text-sm font-bold mb-5">{phase==='locking'?'Locking verified entries…':phase==='seeding'?'Generating secure random seed…':'Cryptographic RNG running…'}</div><div className="relative overflow-hidden rounded-3xl border border-violet-400/30 bg-black/40 p-8 md:p-12 shadow-[0_0_80px_rgba(124,58,237,.2)]"><div className="font-mono text-3xl md:text-6xl font-black tracking-wider text-yellow-300">{phase==='rng'?ticker:'••••••••••••••'}</div><div className="absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-transparent via-violet-400 to-transparent animate-pulse"/></div></div>}
    {phase.startsWith('winner-')&&<div className="my-10"><div className="text-yellow-400 uppercase tracking-[.3em] font-black">Selecting Winner {phase.split('-')[1]}</div><div className="mt-6 font-mono text-4xl md:text-7xl font-black animate-pulse">{ticker}</div></div>}
    {phase==='ready'&&!status.drawn&&<div className="mt-10"><div className="grid grid-cols-2 gap-4 mb-7"><div className="rounded-2xl bg-white/5 border border-white/10 p-5"><div className="text-white/40 text-xs uppercase">Verified tickets</div><div className="text-4xl font-black mt-1">{status.eligible_ticket_count}</div></div><div className="rounded-2xl bg-white/5 border border-white/10 p-5"><div className="text-white/40 text-xs uppercase">Unique entrants</div><div className="text-4xl font-black mt-1">{status.eligible_user_count}</div></div></div><button onClick={start} disabled={!status.can_draw} className="px-12 py-5 rounded-2xl bg-gradient-to-r from-yellow-300 to-yellow-500 text-black text-xl md:text-2xl font-black shadow-[0_0_45px_rgba(250,204,21,.25)] disabled:opacity-40">START RANDOM DRAW</button>{!status.can_draw&&<div className="mt-4 text-rose-300">{status.blocked_reason}</div>}</div>}
    {revealed.length>0&&<div className={`w-full max-w-5xl grid ${revealed.length>1?'md:grid-cols-2':''} gap-5 mt-8`}>{revealed.map(w=><div key={w.place} className="relative overflow-hidden rounded-3xl border border-yellow-300/30 bg-gradient-to-br from-violet-700/80 to-indigo-950 p-7 md:p-9 shadow-[0_0_70px_rgba(124,58,237,.2)]"><div className="absolute -right-8 -top-8 text-[9rem] opacity-[.05] font-black">{w.place}</div><div className="text-yellow-300 text-xs tracking-[.3em] font-black">WINNER #{w.place}</div><div className="mt-3 text-3xl md:text-5xl font-black">£{Number(w.prize_gbp).toLocaleString()}</div><div className="mt-5 text-white/50 text-xs uppercase tracking-widest">Winning Ticket</div><div className="font-mono text-xl md:text-3xl font-black mt-1">{w.ticket_number}</div></div>)}</div>}
    {phase==='complete'&&result&&<div className="mt-8 max-w-4xl w-full rounded-2xl border border-emerald-400/25 bg-emerald-400/5 p-5"><div className="text-emerald-300 text-xl font-black">✓ DRAW VERIFIED</div><div className="grid md:grid-cols-3 gap-3 mt-4 text-left text-xs"><div><span className="text-white/40">RNG</span><div className="font-bold mt-1">{result.rng_algorithm}</div></div><div><span className="text-white/40">Entry snapshot</span><div className="font-mono mt-1">{short(result.ticket_snapshot_sha256)}</div></div><div><span className="text-white/40">Seed verification</span><div className="font-mono mt-1">{short(result.rng_seed_sha256)}</div></div></div><div className="mt-4 text-white/35 text-xs">Drawn {new Date(result.drawn_at).toLocaleString()} • {result.eligible_ticket_count} verified tickets • {result.eligible_user_count} eligible users</div></div>}
    {error&&<div className="mt-5 text-rose-300 font-bold">{error}</div>}
   </main><footer className="text-center text-[10px] uppercase tracking-[.25em] text-white/25">Results are fixed by the server-side cryptographic draw before the visual reveal</footer>
  </div>
 </div>}
