#!/usr/bin/env python3
"""Final preview DB cleanliness check after focused wipe testing."""
from __future__ import annotations

import json
from pathlib import Path

from dotenv import dotenv_values
from pymongo import MongoClient

ROOT = Path('/app')
be = dotenv_values(ROOT / 'backend' / '.env')
client = MongoClient(be['MONGO_URL'])
db = client[(be.get('DB_NAME') or 'gamezoo').strip('"')]

collections = [
    'audit_log', 'winner_audit', 'contests', 'contest_draws', 'game_scores',
    'instant_win_configs', 'instant_win_reveals', 'kyc', 'leaderboard_entries',
    'meera_log', 'notifications', 'orders', 'payment_transactions',
    'postal_entries', 'referrals', 'support_cases', 'tickets', 'user_sessions',
    'wallet_tx', 'winners', 'wallets', 'admin_audit',
]

# Clean leftover QA artifacts only. Also remove the wipe audit rows generated by
# this focused preview verification so the preview DB is left clean for the next
# run; legal docs/settings/users are intentionally untouched.
for col in collections:
    try:
        db[col].delete_many({'qa_run_id': {'$exists': True}})
    except Exception:
        pass
db.users.delete_many({'qa_run_id': {'$exists': True}})
db.admin_audit.delete_many({'action': 'wipe_demo_data', 'by_email': 'bachanta8@gmail.com'})

counts = {col: db[col].count_documents({}) for col in collections}
users = list(db.users.find({}, {'_id': 0, 'email': 1, 'role': 1, 'user_id': 1}))
report = {'counts': counts, 'users': users}
(ROOT / 'test_reports' / 'final_wipe_state_check.json').write_text(json.dumps(report, indent=2, default=str))
print(json.dumps(report, indent=2, default=str))
client.close()